### ISSUE TITLE
raise NoBackendError() audioread.exceptions.NoBackendError

### ISSUE THREAD

**Issue by DanielGuo1** [jonatasgrosman/huggingsound#8]
First of all thank you for your work! 
I am not able to run the `transcibe()` method.

This is my code:
`from huggingsound import SpeechRecognitionModel

model = SpeechRecognitionModel("jonatasgrosman/wav2vec2-large-xlsr-53-german")
path = r"C:/Users/johndoe/PycharmProjects/db_mindbox/kedro_pipeline/data/01_raw/Bond_ueber_das_wetter_und_berlin.mp3"
audio_paths = [path]

transcriptions = model.transcribe(audio_paths)`

I assume my path is not correct, but I already tried different Formats:

* r"C:\\Users\\johndoe\\..."
* r"C:\Users\johndoe\..."
 -> did not work either.

This is the output:

`02/24/2022 11:40:11 - INFO - huggingsound.speech_recognition.model - Loading model...
  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\librosa\core\audio.py", line 149, in load
    with sf.SoundFile(path) as sf_desc:
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'C:/Users/johndoe/PycharmProjects/db_mindbox/kedro_pipeline/data/01_raw/Bond_ueber_das_wetter_und_berlin.mp3': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/johndoe/PycharmProjects/db_mindbox/main.py", line 7, in <module>
    transcriptions = model.transcribe(audio_paths)
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\huggingsound\speech_recognition\model.py", line 108, in transcribe
    waveforms = get_waveforms(paths_batch, sampling_rate)
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\huggingsound\utils.py", line 52, in get_waveforms
    waveform, sr = librosa.load(path, sr=sampling_rate)
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\librosa\core\audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\librosa\core\audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\johndoe\anaconda3\envs\db_mindbox\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

Process finished with exit code 1`

**Comment by DanielGuo1** [comment]
Ok I found a soultion to that error:

I did not installed ffmpeg: 
`conda install -c conda-forge ffmpeg`

**Comment by jonatasgrosman** [comment]
Happy to see you could be able to figure out how to fix the error :)
