### ISSUE TITLE
Issue with ASR inference using language model

### ISSUE THREAD

**Issue by Sathvik833** [jonatasgrosman/huggingsound#88]
I am trying to use the inference boosted by LM technique for ASR, but I am getting an error. Can you please help? I follow the guidelines as described here: https://github.com/jonatasgrosman/huggingsound#inference-boosted-by-a-language-model

 

Model used: https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-english

Error is attached.
![Screenshot 2023-04-17 at 15-55-27 boosted_english - Jupyter Notebook](https://user-images.githubusercontent.com/61035070/232644921-c6d044d1-534b-4dff-9e41-c0997904b4bf.png)

**Comment by lfcnassif** [comment]
Hello,

After issues to use a language model on Windows in the past with the fine tuned portuguese model (#62), I'm trying on Linux now. With both the large 1 billion params portuguese model and with the same English model referenced above I'm getting this error when using the KenshoLMDecoder:
```
>>> decoder = KenshoLMDecoder(model.token_set, lm_path='/home/sepinf/lm_en.binary', unigrams_path='/home/sepinf/unigrams_en.txt' )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sepinf/anaconda3/envs/iped/lib/python3.9/site-packages/huggingsound/speech_recognition/decoder.py", line 674, in __init__
    from pyctcdecode import build_ctcdecoder
  File "/home/sepinf/anaconda3/envs/iped/lib/python3.9/site-packages/pyctcdecode/__init__.py", line 3, in <module>
    from .decoder import BeamSearchDecoderCTC, build_ctcdecoder  # noqa
  File "/home/sepinf/anaconda3/envs/iped/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 94, in <module>
    NpFloat = np.floating[NBitBase]
TypeError: 'type' object is not subscriptable
>>>
```

We are trying to improve our ASR system to transcribe audios recorded by criminals using IM apps. Any help or advice would be greatly appreciated, thank you!
